language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mithrilbp' ]; then cd .. && eval "mv $currentfolder generator-mithrilbp" && cd generator-mithrilbp; fi
